#!/usr/bin/env bash

composer install ## Install Composer dependencies
php artisan key:generate # Make an application key
php artisan migrate # Migrate the database
php artisan db:seed # Seed the database with some basic info
yarn install # Install Yarn dependencies
yarn run dev # Compile frontend assets
