#!/usr/bin/env bash

./vessel init # Set up docker containers etc
./vessel start # Start the docker containers
./vessel composer install ## Install Composre dependencies
./vessel artisan key:generate # Make an application key
./vessel artisan migrate # Migrate the database
./vessel artisan db:seed # Seed the database with some basic info
./vessel yarn install # Install Yarn dependencies
./vessel yarn run dev # Compile frontend assets
